# Generated by Django 4.0.1 on 2022-03-11 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='company_reg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=30)),
                ('filename', models.CharField(max_length=255)),
                ('contact', models.BigIntegerField()),
                ('address', models.TextField()),
            ],
            options={
                'db_table': 'companies',
            },
        ),
    ]
