# Generated by Django 5.0.4 on 2024-04-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0002_company_reg_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company_reg',
            name='first_name',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
