# Generated by Django 5.0.4 on 2024-04-23 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_company_reg_first_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_reg',
            old_name='first_name',
            new_name='fname',
        ),
    ]
