# Generated by Django 5.0.4 on 2024-04-23 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_rename_first_name_company_reg_fname'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company_reg',
            old_name='fname',
            new_name='first_name',
        ),
    ]
