# Generated by Django 4.0.1 on 2022-04-03 12:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('customer', '0004_alter_feedback_user_inquiry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inquiry',
            name='user',
        ),
        migrations.AddField(
            model_name='inquiry',
            name='primary_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='customer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='inquiry',
            name='secondary_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='company', to=settings.AUTH_USER_MODEL),
        ),
    ]
