# Generated by Django 5.0.3 on 2024-04-04 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0005_remove_inquiry_user_inquiry_primary_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReceiverOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Receiver_name', models.CharField(max_length=100)),
                ('Receiver_email', models.EmailField(max_length=254)),
                ('Receiver_phone_number', models.CharField(max_length=15)),
                ('Receiver_alternate_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('Delivery_address_line1', models.CharField(max_length=255)),
                ('Delivery_address_line2', models.CharField(max_length=255)),
                ('Receiver_pincode', models.CharField(max_length=6)),
                ('Receiver_city', models.CharField(max_length=100)),
                ('Receiver_state', models.CharField(max_length=100)),
                ('Receiver_country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Receiverorder',
            },
        ),
        migrations.CreateModel(
            name='SenderOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sender_name', models.CharField(max_length=100)),
                ('Sender_email', models.EmailField(max_length=254)),
                ('Sender_phone_number', models.CharField(max_length=15)),
                ('Sender_alternate_phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('Pickup_address_line1', models.CharField(max_length=255)),
                ('Pickup_address_line2', models.CharField(max_length=255)),
                ('Sender_pincode', models.CharField(max_length=6)),
                ('Sender_city', models.CharField(max_length=100)),
                ('Sender_state', models.CharField(max_length=100)),
                ('Sender_country', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'Senderorder',
            },
        ),
    ]
