# Generated by Django 5.0.4 on 2024-04-07 07:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0010_orderinfo_primary_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='receiverorder',
            name='primary_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='receiver_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='senderorder',
            name='primary_user',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='sender_orders', to=settings.AUTH_USER_MODEL),
        ),
    ]
