# Generated by Django 5.0.4 on 2024-04-11 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0012_orderinfo_height_orderinfo_length_orderinfo_weight_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='height',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='length',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='width',
        ),
    ]
