# Generated by Django 5.0.4 on 2024-04-11 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0014_orderinfo_height_orderinfo_length_orderinfo_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
