# Generated by Django 5.0.4 on 2024-04-13 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0018_alter_orderinfo_height_alter_orderinfo_length_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='unit_price',
        ),
    ]
