# Generated by Django 5.0.4 on 2024-04-20 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0019_remove_orderinfo_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='total',
        ),
    ]
