# Generated by Django 5.0.4 on 2024-04-20 10:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0021_orderinfo_selected_company_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='selected_company_name',
        ),
        migrations.RemoveField(
            model_name='orderinfo',
            name='selected_company_price',
        ),
        migrations.CreateModel(
            name='CompanyOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('order_info', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_orders', to='customer.orderinfo')),
            ],
        ),
    ]
