# Generated by Django 4.0.1 on 2022-04-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_price_reg_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='price_reg',
            name='weight',
            field=models.CharField(default='5kg', max_length=20),
        ),
    ]
