# Generated by Django 4.0.1 on 2022-04-03 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0005_alter_price_reg_weight'),
    ]

    operations = [
        migrations.RenameField(
            model_name='price_reg',
            old_name='weight',
            new_name='package_weight',
        ),
    ]
