# Generated by Django 5.0.4 on 2024-04-15 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0008_alter_price_reg_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price_reg',
            name='company',
        ),
    ]
